//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasxPagar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cierre
    {
        public int id_cierre { get; set; }
        public int id_parametros { get; set; }
        public Nullable<double> monto { get; set; }
    
        public virtual Parametros Parametros { get; set; }
    }
}
