//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasxPagar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database : DbContext
    {
        public Database()
            : base("name=Database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cierre> Cierre { get; set; }
        public virtual DbSet<ConceptosDePago> ConceptosDePago { get; set; }
        public virtual DbSet<DocumentosXPagar> DocumentosXPagar { get; set; }
        public virtual DbSet<GestionDePago> GestionDePago { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
    }
}
