//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasxPagar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionDePago
    {
        public int id_solicitud { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_de_pago { get; set; }
        public Nullable<double> monto { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
