//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasxPagar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int id_usuario { get; set; }
        public string usuario { get; set; }
        public string privilegio { get; set; }
        public string contraseña { get; set; }
    }
}
