//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasxPagar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.DocumentosXPagar = new HashSet<DocumentosXPagar>();
            this.GestionDePago = new HashSet<GestionDePago>();
        }
    
        public int id_proveedor { get; set; }
        public int id_pago { get; set; }
        public string nombre { get; set; }
        public string cedula_RNC { get; set; }
        public string tipo_de_persona { get; set; }
        public Nullable<double> balance { get; set; }
        public string estado { get; set; }
    
        public virtual ConceptosDePago ConceptosDePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosXPagar> DocumentosXPagar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionDePago> GestionDePago { get; set; }
    }
}
